services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: more-light-db
    ports:
      - "5432:5432"
    volumes:
      - more-light-db-data:/var/lib/postgresql/data

volumes:
  more-light-db-data: